[book]
authors = ["Alisa Feistel"]
language = "en"
multilingual = false
src = "src"
title = "Exercises"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "navy"
mathjax-support = true
